import type { PerkDef } from '@/engine/types';

/**
 * Perks are granted two ways: the backstory generator matches them by
 * `affinities`, or story content grants them explicitly with a `grantPerk`
 * effect. A perk with no affinities can only ever be earned.
 */
const list: PerkDef[] = [
  // --- Backstory perks -----------------------------------------------------
  {
    id: 'first-response',
    name: 'First Response',
    description: 'You have set bones in worse places than this. Injuries heal faster, and you steady others when they are hurt.',
    icon: '✚',
    rarity: 'uncommon',
    bonuses: { resilience: 6, empathy: 3 },
    affinities: ['medicine'],
  },
  {
    id: 'clinical-eye',
    name: 'Clinical Eye',
    description: 'You read a body the way other people read a face. You can tell how long someone has been infected.',
    icon: '◉',
    rarity: 'rare',
    bonuses: { cunning: 5, empathy: 3 },
    affinities: ['medicine', 'science'],
  },
  {
    id: 'method',
    name: 'Method',
    description: 'You do not guess. You test, you record, and you are right more often than people who trust their gut.',
    icon: '⌬',
    rarity: 'uncommon',
    bonuses: { cunning: 8 },
    affinities: ['science'],
  },
  {
    id: 'makeshift',
    name: 'Makeshift',
    description: 'Given a length of wire and ten minutes, you can make almost anything work once more.',
    icon: '⚙',
    rarity: 'uncommon',
    bonuses: { scavenge: 7, cunning: 3 },
    affinities: ['engineering', 'software'],
  },
  {
    id: 'cold-boot',
    name: 'Cold Boot',
    description: 'Dead systems are not always dead. You know which ones still have something to say.',
    icon: '⌨',
    rarity: 'rare',
    bonuses: { cunning: 7, scavenge: 3 },
    affinities: ['software'],
  },
  {
    id: 'under-fire',
    name: 'Under Fire',
    description: 'The noise stops mattering. You have been here before and your hands already know what to do.',
    icon: '◈',
    rarity: 'uncommon',
    bonuses: { resolve: 7, resilience: 4 },
    affinities: ['military', 'violence'],
  },
  {
    id: 'reads-a-room',
    name: 'Reads a Room',
    description: 'You clock the exits, the liar, and the one who is about to run — usually in that order.',
    icon: '◎',
    rarity: 'uncommon',
    bonuses: { cunning: 5, empathy: 5 },
    affinities: ['law', 'trade', 'service'],
  },
  {
    id: 'patient',
    name: 'Patient',
    description: 'You have explained the same thing thirty times without raising your voice. People trust that.',
    icon: '✦',
    rarity: 'uncommon',
    bonuses: { empathy: 8 },
    affinities: ['teaching', 'care'],
  },
  {
    id: 'someone-elses-first',
    name: "Someone Else's First",
    description: 'You have spent years putting another person ahead of yourself. It is not a habit you can drop now.',
    icon: '◐',
    rarity: 'rare',
    bonuses: { empathy: 6, resolve: 5 },
    affinities: ['care'],
  },
  {
    id: 'the-long-way',
    name: 'The Long Way',
    description: 'You can walk further than people expect, on less than they think possible.',
    icon: '➤',
    rarity: 'uncommon',
    bonuses: { resilience: 8 },
    affinities: ['athletic', 'outdoors', 'transport'],
  },
  {
    id: 'field-craft',
    name: 'Field Craft',
    description: 'Water, shelter, fire, in that order. You have never needed a shop to eat.',
    icon: '❋',
    rarity: 'uncommon',
    bonuses: { scavenge: 8, resilience: 3 },
    affinities: ['outdoors'],
  },
  {
    id: 'held-the-line',
    name: 'Held the Line',
    description: 'You have been the one people looked at when things went wrong, and you did not look away.',
    icon: '▲',
    rarity: 'rare',
    bonuses: { resolve: 8, empathy: 3 },
    affinities: ['leadership', 'faith'],
  },
  {
    id: 'nothing-left-to-take',
    name: 'Nothing Left to Take',
    description: 'You lost everything before the world did. It made you very hard to frighten.',
    icon: '◇',
    rarity: 'rare',
    bonuses: { resolve: 6, scavenge: 6 },
    affinities: ['hardship', 'isolation', 'loss'],
  },
  {
    id: 'makes-it-mean-something',
    name: 'Makes It Mean Something',
    description: 'You find the shape in things. It is not a survival skill, but people follow you for it anyway.',
    icon: '✧',
    rarity: 'uncommon',
    bonuses: { empathy: 5, cunning: 4 },
    affinities: ['craft'],
  },
  {
    id: 'adaptable',
    name: 'Adaptable',
    description: 'No single thing you have done prepared you for this. All of it together did.',
    icon: '◆',
    rarity: 'common',
    bonuses: { cunning: 4, resolve: 4, scavenge: 3 },
    affinities: ['generalist'],
  },
  {
    id: 'stubborn',
    name: 'Stubborn',
    description: 'You have been told to stop, and you did not.',
    icon: '■',
    rarity: 'common',
    bonuses: { resolve: 5, resilience: 5 },
    affinities: ['generalist'],
  },

  // --- Earned perks --------------------------------------------------------
  {
    id: 'hardened',
    name: 'Hardened',
    description: 'You have stopped counting. Somewhere west of here, that would have worried you.',
    icon: '☠',
    rarity: 'rare',
    bonuses: { resolve: 8, resilience: 5 },
  },
  {
    id: 'quiet-hands',
    name: 'Quiet Hands',
    description: 'You have learned to move through a room full of them and come out the other side.',
    icon: '❍',
    rarity: 'rare',
    bonuses: { cunning: 8 },
  },
  {
    id: 'worth-following',
    name: 'Worth Following',
    description: 'People have chosen to walk beside you when leaving would have been easier.',
    icon: '★',
    rarity: 'unique',
    bonuses: { empathy: 8, resolve: 5 },
  },
  {
    id: 'listener',
    name: 'Listener',
    description: 'You have heard one of them speak, and you did not run. Nothing about the infected reads the same to you now.',
    icon: '👁',
    rarity: 'unique',
    bonuses: { empathy: 6, cunning: 6 },
  },
];

export const perks: Record<string, PerkDef> = Object.fromEntries(list.map((p) => [p.id, p]));
